Coffee house responsive design
GevinduH/coffee-shop pull request #5
Opened 2024-07-26 10:43 UTC by GevinduH

Changes made:

- Designed the webpages according the Figma design
- Made the website responsive.
- Added new buttons.
- Added new stylings to the CSS file.

2024-07-31 11:30 UTC, vieraboschkova requested changes
Overall, it looks great, I checked on my mobile as well, the layout doesnt break, good job. 
(To test your design on various devices and browsers you can also use browserstack, they have a free account with some time limits.) 

apart from minor in code comments, we need some more changes:
## on the 1440 view:
  - the menu button with the cup must be aligned accorging to wireframes 
<img width="184" alt="Screenshot 2024-07-31 at 13 03 49" src="https://github.com/user-attachments/assets/e56393c6-b4ee-4d16-a613-a2caa5fbf1d7">

  - the inner circles of the menu options button should be circles (valid for all views): 
<img width="333" alt="Screenshot 2024-07-31 at 13 07 04" src="https://github.com/user-attachments/assets/e4901917-df30-436b-9799-6a3952d00f7c">

  - the is a rather big discrepancy with the wireframes under the images on the home page, change to have the difference from wireframe  max ±15px :
<img width="1082" alt="Screenshot 2024-07-31 at 13 09 42" src="https://github.com/user-attachments/assets/ea8e98a0-bba0-4e06-adbf-1ba3fd08c838">

## on 768 px

- burger placement 
<img width="131" alt="Screenshot 2024-07-31 at 13 15 02" src="https://github.com/user-attachments/assets/6708c212-1a46-4205-b5e0-efaa6d648ac1">

- all the sections below hero must be pushed down a bit 
<img width="757" alt="Screenshot 2024-07-31 at 13 16 05" src="https://github.com/user-attachments/assets/d2fd1306-39b8-4273-9351-818faa9067ac">

- the div with class "download-text" has different alignments, goes with the lines of the images: 
<img width="811" alt="Screenshot 2024-07-31 at 13 19 43" src="https://github.com/user-attachments/assets/8bf9c990-2dd4-4f1b-8f70-04d80a6dc1b2">

- all content in the menu options page must be closer to wireframes, images should be centered on the page, the distance on the left is smaller than on the right: 
<img width="730" alt="Screenshot 2024-07-31 at 13 21 26" src="https://github.com/user-attachments/assets/cc21e563-440c-4d9b-abad-428e75f91b00">

## on 380 px:
- in menu options, the display is not centered
- hero image seems to have wrong dimensions
<img width="468" alt="Screenshot 2024-07-31 at 13 26 48" src="https://github.com/user-attachments/assets/11ae5ef1-ba01-407c-ac50-46e9338cf09d">

Thank you!

2024-07-31 11:30 UTC, vieraboschkova commented on docs/coffee.html
> +            <h3 style="padding-bottom: 10px">contact us</h3>
Maybe you could use a class to add paddings? Instead of inline styles?

2024-07-31 11:30 UTC, vieraboschkova commented on docs/index.html
> +            <h3 style="padding-bottom: 10px">contact us</h3>
Perhaps use a class to style it?

2024-07-31 11:30 UTC, vieraboschkova commented on docs/style.css
> +    /* display: flex;
Needed?

2024-07-31 11:30 UTC, vieraboschkova commented on docs/style.css
> +    /* justify-content: space-between; */
Needed?

2024-07-31 11:30 UTC, vieraboschkova commented on docs/style.css
> +    /* gap: 20px; */
Probably not necessary as well?

2024-07-31 11:30 UTC, vieraboschkova commented on docs/style.css
> +
Did you manage to hook any formatter to your css files?

2024-08-06 09:40 UTC, GevinduH commented on docs/coffee.html
> +            <h3 style="padding-bottom: 10px">contact us</h3>
Changed.

2024-08-06 09:41 UTC, GevinduH commented on docs/index.html
> +            <h3 style="padding-bottom: 10px">contact us</h3>
Done.

2024-08-06 10:06 UTC, GevinduH commented on docs/style.css
> +    /* display: flex;
No. I was testing with dev tools and forgot to remove it from the css file. I cleared them now.

2024-08-06 10:06 UTC, GevinduH commented on docs/style.css
> +    /* justify-content: space-between; */
removed.

2024-08-06 10:07 UTC, GevinduH commented on docs/style.css
> +    /* gap: 20px; */
Yes.

2024-08-06 10:08 UTC, GevinduH commented on docs/style.css
> +
Still no. Are there any issues with the format?

2024-08-06 11:11 UTC, vieraboschkova commented on docs/style.css
> +
Keeps spaces, empty lines and the formatting of the file consistent, otherwise it is really hard to make it stick to a pattern.

2024-08-07 06:55 UTC, vieraboschkova approved these changes
Great job fixing the layouts! I think the only thing that's still missing are the menu options buttons, but you can change it in the next part of this project.

Good job!

2024-08-09 06:20 UTC, merged